package hashtable;

import java.util.HashMap;
import java.util.Map;

/**
 * Given two strings s and t which consist of only lowercase letters.

 * String t is generated by random shuffling string s and then add one more letter at a random position.

 * Find the letter that was added in t.
 * Input:
	s = "abcd"
	t = "abcde"

   Output:
	e

   Explanation:
	'e' is the letter that was added.
 
 */
public class FindTheDifference {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}
	
	public char findTheDifference(String s, String t) {
		char result = '\0';
		char[] sArr = s.toCharArray();
		char[] tArr = t.toCharArray();
		
		Map<Character,Integer> mapS = new HashMap<Character,Integer>();
		
		for (char charS : sArr) {
			if (mapS.containsKey(charS)) {
				mapS.put(charS, mapS.get(charS) + 1);
			} else {
				mapS.put(charS, 1);
			}
		}
		
		for (char charT : tArr) {
			if (mapS.containsKey(charT)) {
				mapS.put(charT, mapS.get(charT)-1);
				
				if (mapS.get(charT) < 0) {
					result = charT;
				}
			} else {
				result = charT;
			}
		}
		
		return result;
	}
	
	
	
}
